
version: '3.8'

services:
  app:
    build: 
      context: .
      target: production
    container_name: system-complaint
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_MSAL_TENANT_ID=${VITE_MSAL_TENANT_ID}
      - VITE_MSAL_CLIENT_ID=${VITE_MSAL_CLIENT_ID}
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:80/ || exit 1
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
